# Generated by Django 3.1.7 on 2021-05-12 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Grado', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombrePeriodo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=32)),
                ('Apellido', models.CharField(max_length=32)),
                ('Celular', models.CharField(blank=True, max_length=10)),
                ('CURP', models.CharField(max_length=18)),
                ('FechaNacimiento', models.DateTimeField()),
                ('Direccion', models.CharField(max_length=100)),
                ('Correo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Materia', models.CharField(max_length=50)),
                ('Horario', models.CharField(max_length=8)),
                ('ID_Docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.docente')),
                ('ID_Periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.periodo')),
            ],
        ),
        migrations.AddField(
            model_name='docente',
            name='ID_Usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.usuario'),
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bimestre1', models.FloatField()),
                ('Bimestre2', models.FloatField()),
                ('Bimestre3', models.FloatField()),
                ('Bimestre4', models.FloatField()),
                ('Bimestre5', models.FloatField()),
                ('Promedio', models.FloatField()),
                ('ID_Materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.materia')),
                ('NoControl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.alumno')),
            ],
        ),
        migrations.AddField(
            model_name='alumno',
            name='ID_Usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.usuario'),
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Permisos', models.BooleanField(default=False)),
                ('ID_Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.usuario')),
            ],
        ),
    ]
